name: kikibytes_pages
description: KikiBytes Labs marketing website
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
